## Week 6 Lab Assignment
# CIS 2266
## NumPy Exercise
### E Jinq Heng

- Create a new Jupyter Notebook
- Import numpy 
- Work the problems below (3 points each)
- Submit an html output of your work to the dropbox for grading

First, make a common array to work with.

In [1]:
import numpy as np
np.random.seed(21)
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

### 1. What is the average value of the second column?

In [2]:
avg = np.average(random_integers[:20, 1:2])
print(avg)

214895.8


### 2. What is the average value of the first 5 rows of the third and fourth columns?

In [3]:
avg = np.average(random_integers[:5, 2:4])
print(avg)

286058.5


### 3. Create a 10 x 10 slice from of random_integers array, named arrayTenByTen, that started at 0:0 from random_integers

In [4]:
arrayTenByTen = random_integers.reshape((10,10))
print(arrayTenByTen)

[[ 80842 333008 202553 140037  81969  63857  42105 261540 481981 176739]
 [489984 326386 110795 394863  25024  38317  49982 408830 485118  16119]
 [407675 231729 265455 109413 103399 174677 343356 301717 224120 401101]
 [140473 254634 112262  25063 108262 375059 406983 208947 115641 296685]
 [444899 129585 171318 313094 425041 188411 335140 141681  59641 211420]
 [287650   8973 477425 382803 465168   3975  32213 160603 275485 388234]
 [246225  56174 244097   9350 496966 225516 273338  73335 283013 212813]
 [ 38175 282399 318413 337639 379802 198049 101115 419547 260219 325793]
 [148593 425024 348570 117968 107007  52547 180346 178760 305186 262153]
 [ 11835 449971 494184 472031 353049 476442  35455 191553 384154  29917]]


### 4. Create a new array from the arrayTenByTen that is one rank and called arrayTenFlat

In [5]:
arrayTenFlat = arrayTenByTen.reshape((100,))
print(arrayTenFlat)
print("\nThe shape of the arrayTenFlat is", arrayTenFlat.shape)

[ 80842 333008 202553 140037  81969  63857  42105 261540 481981 176739
 489984 326386 110795 394863  25024  38317  49982 408830 485118  16119
 407675 231729 265455 109413 103399 174677 343356 301717 224120 401101
 140473 254634 112262  25063 108262 375059 406983 208947 115641 296685
 444899 129585 171318 313094 425041 188411 335140 141681  59641 211420
 287650   8973 477425 382803 465168   3975  32213 160603 275485 388234
 246225  56174 244097   9350 496966 225516 273338  73335 283013 212813
  38175 282399 318413 337639 379802 198049 101115 419547 260219 325793
 148593 425024 348570 117968 107007  52547 180346 178760 305186 262153
  11835 449971 494184 472031 353049 476442  35455 191553 384154  29917]

The shape of the arrayTenFlat is (100,)


### 5. What is the sum of arrayTenFlat?

In [6]:
print(np.sum(arrayTenFlat))

23526182


### 6. Iterate through arrayTenFlat

In [7]:
for i in arrayTenFlat:
    print(i)

80842
333008
202553
140037
81969
63857
42105
261540
481981
176739
489984
326386
110795
394863
25024
38317
49982
408830
485118
16119
407675
231729
265455
109413
103399
174677
343356
301717
224120
401101
140473
254634
112262
25063
108262
375059
406983
208947
115641
296685
444899
129585
171318
313094
425041
188411
335140
141681
59641
211420
287650
8973
477425
382803
465168
3975
32213
160603
275485
388234
246225
56174
244097
9350
496966
225516
273338
73335
283013
212813
38175
282399
318413
337639
379802
198049
101115
419547
260219
325793
148593
425024
348570
117968
107007
52547
180346
178760
305186
262153
11835
449971
494184
472031
353049
476442
35455
191553
384154
29917


### 7. What is the value of the element (2,4) in random_integers array?

In [8]:
print(random_integers[2,4])

25024


### 8. What is the data type of arrayTenFlat?

In [9]:
arrayTenFlat.dtype

dtype('int32')

### 9. In arrayTenFlat replace the value in index 5 with 42

In [10]:
arrayTenFlat[5] = 42
print(arrayTenFlat)

[ 80842 333008 202553 140037  81969     42  42105 261540 481981 176739
 489984 326386 110795 394863  25024  38317  49982 408830 485118  16119
 407675 231729 265455 109413 103399 174677 343356 301717 224120 401101
 140473 254634 112262  25063 108262 375059 406983 208947 115641 296685
 444899 129585 171318 313094 425041 188411 335140 141681  59641 211420
 287650   8973 477425 382803 465168   3975  32213 160603 275485 388234
 246225  56174 244097   9350 496966 225516 273338  73335 283013 212813
  38175 282399 318413 337639 379802 198049 101115 419547 260219 325793
 148593 425024 348570 117968 107007  52547 180346 178760 305186 262153
  11835 449971 494184 472031 353049 476442  35455 191553 384154  29917]


### 10. Save the array random_integers to a file.  List the directory showing the saved array.

In [11]:
np.save("saved_array", random_integers)
load = np.load("saved_array.npy")
print(load)

[[ 80842 333008 202553 140037  81969]
 [    42  42105 261540 481981 176739]
 [489984 326386 110795 394863  25024]
 [ 38317  49982 408830 485118  16119]
 [407675 231729 265455 109413 103399]
 [174677 343356 301717 224120 401101]
 [140473 254634 112262  25063 108262]
 [375059 406983 208947 115641 296685]
 [444899 129585 171318 313094 425041]
 [188411 335140 141681  59641 211420]
 [287650   8973 477425 382803 465168]
 [  3975  32213 160603 275485 388234]
 [246225  56174 244097   9350 496966]
 [225516 273338  73335 283013 212813]
 [ 38175 282399 318413 337639 379802]
 [198049 101115 419547 260219 325793]
 [148593 425024 348570 117968 107007]
 [ 52547 180346 178760 305186 262153]
 [ 11835 449971 494184 472031 353049]
 [476442  35455 191553 384154  29917]]


In [12]:
import os
print(os.path.realpath("saved_array.npy"))

C:\Users\JaniceJ\Documents\Fall 2019\CIS2266 Python for Data Analytics\saved_array.npy
