### NumPy

### Array of the same value

In [2]:
# get numpy (preinstalled in Anaconda)
import numpy as np

In [3]:
# np and the [TAB] key
np.version

<module 'numpy.version' from 'C:\\Users\\JaniceJ\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [6]:
# rank 1 array [,,]
a = np.array([1,2,3])

In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
print("The Shape")
a.shape

The Shape


(3,)

In [9]:
print(a)

[1 2 3]


In [13]:
# rank 2 array ([[,],[,]])
b = np.array([[2.5,6.1],[8.1,1.2]])

In [14]:
print(b)
print("----shape----")
b.shape

[[2.5 6.1]
 [8.1 1.2]]
----shape----


(2, 2)

In [15]:
# create empty..zero..array
c = np.zeros((2,2))
print(c)

[[0. 0.]
 [0. 0.]]


In [17]:
# dtype to see what kind of array it is
c.dtype

dtype('float64')

In [18]:
# full array function
# ones
d = np.ones((3,3))
print(d)
d.dtype

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [19]:
# anynumber
e = np.full((4,4),7)
print(e)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [28]:
# random number
f = np.random.random((5,5))
print(f)

[[0.0647507  0.59301248 0.26354204 0.05531653 0.88990367]
 [0.70273817 0.75791406 0.55928974 0.77339229 0.30098702]
 [0.44285859 0.91634345 0.29149559 0.16134244 0.47718203]
 [0.15053261 0.83401774 0.96901432 0.89755328 0.6909616 ]
 [0.93858127 0.57532875 0.6914822  0.9222319  0.67075964]]


dtype('float64')

In [32]:
g = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(g)
g.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

In [33]:
# two rows and cols
# [ : first x rows, start col : end before col ]
# first 2 rows, starting at 1 to before 3
f = g[:2, 1:3]
print(f)

[[2 3]
 [6 7]]


In [34]:
# print value at [0,2]
print(g[0,2])

3


In [35]:
print(g)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
# change the value at [0,0]
g[0,0] = 77

In [37]:
print(g)

[[77  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
g.shape

(3, 4)

In [43]:
h = g.reshape((12,))
print(h)

[77  2  3  4  5  6  7  8  9 10 11 12]


In [44]:
h.dtype

dtype('int32')

In [47]:
# force the type of the array
nal = np.array([1,5,2], dtype=np.float64)
print(nal)
nal.dtype

[1. 5. 2.]


dtype('float64')

## Math 

In [50]:
na2 = np.array([3.33, 4.44], dtype = np.float64)
print(na2)
na3 = np.array([1.53, 2.32], dtype = np.float64)
print(na3)
print("-------")
# must be of the same dimensions
print(na2 + na3)

[3.33 4.44]
[1.53 2.32]
-------
[4.86 6.76]


In [51]:
# subtraction
print(na2 - na3)

[1.8  2.12]


In [52]:
# multiplication
print(na2 * na3)

[ 5.0949 10.3008]


In [53]:
#division
print(na2 / na3)

[2.17647059 1.9137931 ]


In [59]:
# verticle
print(na2)
print(na3)
print("-----------")
print(na2 + na3)

[3.33 4.44]
[1.53 2.32]
-----------
[4.86 6.76]


In [63]:
# horizontal
print(na2)
print(na3)
print("--down--")
print(na2 + na3)
print("--across--")
print(na3)
print(np.sum(na3, axis = 0))

[3.33 4.44]
[1.53 2.32]
--down--
[4.86 6.76]
--across--
[1.53 2.32]
3.8499999999999996


In [65]:
# broadcasting
xx = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(xx)
xx.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [66]:
v = np.array([1,0,1])
print(v)

[1 0 1]


In [67]:
# tile
vv = np.tile(v, (4,1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [68]:
print(xx + vv)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [69]:
# print everything that was ran on this notebook
%history

# get numpy (preinstalled in Anaconda)
import numpy as np
# get numpy (preinstalled in Anaconda)
import numpy as np
# np and the [TAB] key
np.version
a = np.array{[1,2,3]}
print(type(a))
a = np.array([1,2,3])
print(type(a))
print("The Shape")
a.shape
print(a)
# rank 2 array
b = np.array()
# rank 2 array
b = np.array([2.5,6.1],[8.1,1.2])
# rank 2 array
b = np.array([2.5,6.1],[8.0,1.2])
# rank 2 array ([[,],[,]])
b = np.array([[2.5,6.1],[8.1,1.2]])
print(b)
print("----shape----")
b.shape
# create empty..zero..array
c = np.zeros((2,2))
print(c)
b.dtype
c.dtype
# full array function
# ones
d = np.ones((3,3))
print(d)
d.dtype
# anynumber
e = np.full((4,4),7)
print(e)
# random number
f = np.random.random
# random number
f = np.random.random((5,5))
# random number
f = np.random.random((5,5))
print(f)
# random number
f = np.random.random_integer((5,5))
print(f)
# random number
f = np.random.randint((5,5))
print(f)
# random number
f = np.random.random((5,5))
print(f)
# random number
f = np.rand

In [70]:
%history -n

   1:
# get numpy (preinstalled in Anaconda)
import numpy as np
   2:
# get numpy (preinstalled in Anaconda)
import numpy as np
   3:
# np and the [TAB] key
np.version
   4: a = np.array{[1,2,3]}
   5: print(type(a))
   6: a = np.array([1,2,3])
   7: print(type(a))
   8:
print("The Shape")
a.shape
   9: print(a)
  10:
# rank 2 array
b = np.array()
  11:
# rank 2 array
b = np.array([2.5,6.1],[8.1,1.2])
  12:
# rank 2 array
b = np.array([2.5,6.1],[8.0,1.2])
  13:
# rank 2 array ([[,],[,]])
b = np.array([[2.5,6.1],[8.1,1.2]])
  14:
print(b)
print("----shape----")
b.shape
  15:
# create empty..zero..array
c = np.zeros((2,2))
print(c)
  16: b.dtype
  17: c.dtype
  18:
# full array function
# ones
d = np.ones((3,3))
print(d)
d.dtype
  19:
# anynumber
e = np.full((4,4),7)
print(e)
  20:
# random number
f = np.random.random
  21:
# random number
f = np.random.random((5,5))
  22:
# random number
f = np.random.random((5,5))
print(f)
  23:
# random number
f = np.random.random_integer((5,5))
print